const stratagems = [
  {
    type: 'Supply',
    subtype: 'Backpacks',
    name: 'LIFT-850 Jump Pack',
    sequence: ['Down', 'Up', 'Up', 'Down', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-backpacks/LIFT-850icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Backpacks',
    name: 'B-1 Supply Pack',
    sequence: ['Down', 'Left', 'Down', 'Up', 'Up', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-backpacks/B-1icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Backpacks',
    name: 'AX/LAS-5 "Guard Dog" Rover',
    sequence: ['Down', 'Up', 'Left', 'Up', 'Right', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-backpacks/AX-LAS-5icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Backpacks',
    name: 'SH-20 Ballistic Shield Backpack',
    sequence: ['Down', 'Left', 'Down', 'Down', 'Up', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-backpacks/SH-20icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Backpacks',
    name: 'SH-32 Shield Generator Pack',
    sequence: ['Down', 'Up', 'Left', 'Right', 'Left', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-backpacks/SH-32icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Backpacks',
    name: 'AX/AR-23 "Guard Dog"',
    sequence: ['Down', 'Up', 'Left', 'Up', 'Right', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-backpacks/AX-AR-23icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'MG-43 Machine Gun',
    sequence: ['Down', 'Left', 'Down', 'Up', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/MG-43icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'APW-1 Anti-Materiel Rifle',
    sequence: ['Down', 'Left', 'Right', 'Up', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/APW-1icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'M-105 Stalwart',
    sequence: ['Down', 'Left', 'Down', 'Up', 'Up', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/M-105icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'EAT-17 Expendable Anti-tank',
    sequence: ['Down', 'Down', 'Left', 'Up', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/EAT-17icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'GR-8 Recoilless Rifle',
    sequence: ['Down', 'Left', 'Right', 'Right', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/GR-8icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'FLAM-40 Flamethrower',
    sequence: ['Down', 'Left', 'Right', 'Right', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/FLAM-40icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'AC-8 Autocannon',
    sequence: ['Down', 'Left', 'Down', 'Up', 'Up', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/AC-8icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'RS-422 Railgun',
    sequence: ['Down', 'Right', 'Down', 'Up', 'Left', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/RS-422icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'FAF-14 SPEAR Launcher',
    sequence: ['Down', 'Down', 'Up', 'Down', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/FAF-14icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'GL-21 Grenade Launcher',
    sequence: ['Down', 'Left', 'Up', 'Left', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/GL-21icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'LAS-98 Laser Cannon',
    sequence: ['Down', 'Left', 'Down', 'Up', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/LAS-98icon.webp',
  },
  {
    type: 'Supply',
    subtype: 'Secondary Weapons',
    name: 'ARC-3 Arc Thrower',
    sequence: ['Down', 'Right', 'Down', 'Up', 'Left', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/supply-secondary/ARC-3icon.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'Reinforce',
    sequence: ['Up', 'Down', 'Right', 'Left', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/Reinforceicon.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'SOS Beacon',
    sequence: ['Up', 'Down', 'Left', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/SOSicon.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'Resupply',
    sequence: ['Down', 'Down', 'Up', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/ResupplyIcon.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'NUX-223 Hellbomb',
    sequence: ['Down', 'Up', 'Left', 'Down', 'Up', 'Right', 'Down', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/Strat_NUX-223_Hellbomb_mk1.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'SSSD Delivery',
    sequence: ['Down', 'Down', 'Down', 'Up', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/DeliverSSSDicon.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'Seismic Probe',
    sequence: ['Up', 'Up', 'Left', 'Right', 'Down', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/Seismic_probe_icon.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'Upload Data',
    sequence: ['Down', 'Down', 'Up', 'Up', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/DeliverSSSDicon.webp',
  },
  {
    type: 'Mission',
    subtype: '',
    name: 'Eagle Rearm',
    sequence: ['Up', 'Up', 'Left', 'Up', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/mission/HD2_Eagle_Rearm_Icon.webp',
  },
  // {
  //   type: 'Mission',
  //   subtype: '',
  //   name: 'Illumination Flare',
  //   sequence: ['Left', 'Left', 'Right', 'Right'],
  //   image: '',
  // },
  {
    type: 'Defensive',
    subtype: '',
    name: 'E/MG-101 HMG Emplacement',
    sequence: ['Down', 'Up', 'Left', 'Right', 'Right', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/HMGTurreticon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'FX-12 Shield Generator Relay',
    sequence: ['Down', 'Down', 'Left', 'Right', 'Left', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Shieldrelayicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'A/ARC-3 Tesla Tower',
    sequence: ['Down', 'Up', 'Right', 'Up', 'Left', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Teslaicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'MD-6 Anti-Personnel Minefield',
    sequence: ['Down', 'Left', 'Up', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Minefieldicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'MD-I4 Incendiary Mines',
    sequence: ['Down', 'Left', 'Left', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Fireminefieldicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'A/MG-43 Machine Gun Sentry',
    sequence: ['Down', 'Up', 'Right', 'Right', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/MGsentryicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'A/G-16 Gatling Sentry',
    sequence: ['Down', 'Up', 'Right', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Gatlingsentryicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'A/M-12 Mortar Sentry',
    sequence: ['Down', 'Up', 'Right', 'Right', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Mortarsentryicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'A/AC-8 Autocannon Sentry',
    sequence: ['Down', 'Up', 'Right', 'Up', 'Left', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Autocannoasentryicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'A/MLS-4X Rocket Sentry',
    sequence: ['Down', 'Up', 'Right', 'Right', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/Missilesentryicon.webp',
  },
  {
    type: 'Defensive',
    subtype: '',
    name: 'A/M-23 EMS Mortar Sentry	',
    sequence: ['Down', 'Up', 'Right', 'Down', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/defensive/EMSmortaricon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Gatling Barrage	',
    sequence: ['Right', 'Down', 'Left', 'Up', 'Up'],
    image: '',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Airburst Strike',
    sequence: ['Right', 'Right', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalAirbursticon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital 120MM HE Barrage',
    sequence: ['Right', 'Right', 'Down', 'Left', 'Right', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/Orbital120icon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital 380MM HE Barrage',
    sequence: ['Right', 'Down', 'Up', 'Up', 'Left', 'Down', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/Orbital380icon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Walking Barrage',
    sequence: ['Right', 'Down', 'Right', 'Down', 'Right', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalWalkingicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Laser',
    sequence: ['Right', 'Down', 'Up', 'Right', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalLasericon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Railcannon Strike',
    sequence: ['Right', 'Up', 'Down', 'Down', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalRailcannonicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Precision Strike',
    sequence: ['Right', 'Right', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalPrecisionicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Gas Strike',
    sequence: ['Right', 'Right', 'Down', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalGasicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital EMS Strike',
    sequence: ['Right', 'Right', 'Left', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalEMSicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Orbital',
    name: 'Orbital Smoke Strike',
    sequence: ['Right', 'Right', 'Down', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/oribtal-offensive/OrbitalSmokeicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Eagle',
    name: 'Eagle Strafing Run',
    sequence: ['Up', 'Right', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/offensive-eagle/EagleStrafingicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Eagle',
    name: 'Eagle Airstrike',
    sequence: ['Up', 'Right', 'Down', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/offensive-eagle/EagleAirstrikeicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Eagle',
    name: 'Eagle Cluster Bomb',
    sequence: ['Up', 'Right', 'Down', 'Down', 'Right'],
    image: 'stratagem-hero/client/components/stratagem-images/offensive-eagle/EagleClusterbombicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Eagle',
    name: 'Eagle Napalm Airstrike',
    sequence: ['Up', 'Right', 'Down', 'Up'],
    image: 'stratagem-hero/client/components/stratagem-images/offensive-eagle/EagleNapalmicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Eagle',
    name: 'Eagle Smoke Strike',
    sequence: ['Up', 'Right', 'Up', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/offensive-eagle/EagleSmokeicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Eagle',
    name: 'Eagle 110MM Rocket Pods',
    sequence: ['Up', 'Right', 'Up', 'Left'],
    image: 'stratagem-hero/client/components/stratagem-images/offensive-eagle/EagleRocketpodicon.webp',
  },
  {
    type: 'Offensive',
    subtype: 'Eagle',
    name: 'Eagle 500kg Bomb',
    sequence: ['Up', 'Right', 'Down', 'Down', 'Down'],
    image: 'stratagem-hero/client/components/stratagem-images/offensive-eagle/Eagle500icon.webp',
  },
  // {
  //   type: '',
  //   subtype: '',
  //   name: '',
  //   sequence: ['', '', '', '', '', '', '', '', '', ''],
  // },
  // {
  //   type: '',
  //   subtype: '',
  //   name: '',
  //   sequence: ['', '', '', '', '', '', '', '', '', ''],
  // },
];

export default stratagems;
